import type { Patient } from "../types/patient.types"

export const mockPatients: Patient[] = [
  {
    id: "pat_1",
    firstName: "María",
    lastName: "González",
    documentId: "0102030405",
    birthDate: "1990-04-12",
    gender: "femenino",
    phone: "0991234567",
    email: "maria.gonzalez@mail.com",
    address: "Av. Amazonas N34-12, Quito",
    notes: "Alergia a la penicilina.",
    notificationsEnabled: true,
    medicalHistory: "Hipertensión controlada y controles periódicos odontológicos.",
    allergies: "Penicilina, mariscos.",
    emergencyContactName: "Luis González",
    emergencyContactPhone: "0999988776",
    insuranceProvider: "SIS",
    insurancePolicy: "POL-1048",
    consentSigned: true,
    treatmentStatus: "en seguimiento",
    lastVisitAt: "2026-09-08",
    createdAt: "2025-11-02T10:00:00.000Z",
  },
  {
    id: "pat_2",
    firstName: "Carlos",
    lastName: "Pérez",
    documentId: "0203040506",
    birthDate: "1985-08-23",
    gender: "masculino",
    phone: "0987654321",
    email: "carlos.perez@mail.com",
    address: "Calle Bolívar 456, Quito",
    notes: "",
    notificationsEnabled: true,
    medicalHistory: "Sin antecedentes relevantes.",
    allergies: "No registra",
    emergencyContactName: "Ana Pérez",
    emergencyContactPhone: "0988877665",
    insuranceProvider: "Insurac",
    insurancePolicy: "INS-8291",
    consentSigned: true,
    treatmentStatus: "activo",
    lastVisitAt: "2026-09-10",
    createdAt: "2025-11-15T14:30:00.000Z",
  },
  {
    id: "pat_3",
    firstName: "Sofía",
    lastName: "Ramírez",
    documentId: "0304050607",
    birthDate: "2001-01-05",
    gender: "femenino",
    phone: "0976543210",
    email: "",
    address: "",
    notes: "Paciente en tratamiento de ortodoncia.",
    notificationsEnabled: true,
    medicalHistory: "Ortodoncia con seguimiento mensual.",
    allergies: "No registra",
    emergencyContactName: "Marta Ramírez",
    emergencyContactPhone: "0976655443",
    insuranceProvider: "Mutualista",
    insurancePolicy: "MUT-5521",
    consentSigned: false,
    treatmentStatus: "pendiente",
    lastVisitAt: "2026-09-05",
    createdAt: "2025-12-01T09:15:00.000Z",
  },
  {
    id: "pat_4",
    firstName: "Jorge",
    lastName: "Flores",
    documentId: "0405060708",
    birthDate: "1978-06-30",
    gender: "masculino",
    phone: "0965432109",
    email: "jorge.flores@mail.com",
    address: "Av. 6 de Diciembre 789, Quito",
    notes: "",
    notificationsEnabled: false,
    medicalHistory: "Diabetes tipo 2 en control.",
    allergies: "Ninguna",
    emergencyContactName: "Patricia Flores",
    emergencyContactPhone: "0965544332",
    insuranceProvider: "IESS",
    insurancePolicy: "IESS-9982",
    consentSigned: true,
    treatmentStatus: "inactivo",
    lastVisitAt: "2026-08-22",
    createdAt: "2026-01-10T11:45:00.000Z",
  },
  {
    id: "pat_5",
    firstName: "Valentina",
    lastName: "Suárez",
    documentId: "0506070809",
    birthDate: "1995-11-18",
    gender: "otro",
    phone: "0954321098",
    email: "valentina.suarez@mail.com",
    address: "",
    notes: "",
    notificationsEnabled: true,
    medicalHistory: "Control preventivo cada seis meses.",
    allergies: "No registra",
    emergencyContactName: "Ricardo Suárez",
    emergencyContactPhone: "0951234567",
    insuranceProvider: "Claro Salud",
    insurancePolicy: "CS-4400",
    consentSigned: true,
    treatmentStatus: "activo",
    lastVisitAt: "2026-09-12",
    createdAt: "2026-02-20T16:20:00.000Z",
  },
]
