import type { InventoryItem, StockMovement } from "../types/inventory.types"

export const mockInventoryItems: InventoryItem[] = [
  {
    id: "inv_1",
    name: "Guantes de nitrilo (caja x100)",
    category: "Bioseguridad",
    unit: "caja",
    stock: 18,
    minStock: 10,
    unitCost: 8.5,
    supplier: "Distribuidora Médica S.A.",
    createdAt: "2025-10-01T08:00:00.000Z",
  },
  {
    id: "inv_2",
    name: "Anestesia local (cartucho)",
    category: "Odontología",
    unit: "unidad",
    stock: 6,
    minStock: 15,
    unitCost: 1.2,
    supplier: "Farma Dental",
    createdAt: "2025-10-05T08:00:00.000Z",
  },
  {
    id: "inv_3",
    name: "Brackets metálicos",
    category: "Ortodoncia",
    unit: "unidad",
    stock: 120,
    minStock: 40,
    unitCost: 0.9,
    supplier: "OrtoSupply",
    createdAt: "2025-10-10T08:00:00.000Z",
  },
  {
    id: "inv_4",
    name: "Resina compuesta",
    category: "Odontología",
    unit: "jeringa",
    stock: 9,
    minStock: 8,
    unitCost: 15.0,
    supplier: "Farma Dental",
    createdAt: "2025-10-15T08:00:00.000Z",
  },
  {
    id: "inv_5",
    name: "Alcohol antiséptico 70% (litro)",
    category: "Bioseguridad",
    unit: "litro",
    stock: 3,
    minStock: 5,
    unitCost: 3.4,
    supplier: "Distribuidora Médica S.A.",
    createdAt: "2025-10-20T08:00:00.000Z",
  },
]

export const mockStockMovements: StockMovement[] = [
  {
    id: "mov_1",
    itemId: "inv_2",
    type: "salida",
    quantity: 4,
    reason: "Uso en tratamiento de endodoncia",
    createdAt: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "mov_2",
    itemId: "inv_1",
    type: "entrada",
    quantity: 20,
    reason: "Compra a proveedor",
    createdAt: "2026-01-05T09:00:00.000Z",
  },
  {
    id: "mov_3",
    itemId: "inv_5",
    type: "salida",
    quantity: 2,
    reason: "Reposición en consultorio",
    createdAt: "2026-01-12T11:30:00.000Z",
  },
]
