import { test, expect, type Page } from "@playwright/test"

async function login(page: Page, role = "admin") {
  await page.goto("/login")
  await page.getByLabel("Correo electrónico").fill(`${role}@clinica.com`)
  await page.locator("#password").fill(`${role}123`)
  await page.getByRole("button", { name: "Ingresar", exact: true }).click()
  await page.getByRole("button", { name: "Continuar", exact: true }).click()
  await expect(page).toHaveURL(/\/$/)
}
const frameOf = (page: Page) => page.frameLocator('iframe[title="Odontograma y periodontograma del paciente"]')
async function openDental(page: Page, id = "pat_1") {
  await page.goto(`/historial-clinico/paciente/${id}/odontologia`)
  await expect(frameOf(page).locator("#toothGrid")).toBeVisible()
  await expect(page.getByRole("button", { name: "Guardar visita", exact: true })).toBeEnabled()
}

test("odontograma original, temas, visitas, adjuntos y aislamiento por paciente", async ({ page }) => {
  const errors: string[] = []
  page.on("pageerror", (error) => errors.push(error.message))
  await login(page)
  const originalTokens = await page.evaluate(() => ["--background", "--foreground", "--primary"].map((key) => getComputedStyle(document.documentElement).getPropertyValue(key)))
  await openDental(page)
  expect(await page.evaluate(() => ["--background", "--foreground", "--primary"].map((key) => getComputedStyle(document.documentElement).getPropertyValue(key)))).toEqual(originalTokens)
  const editor = frameOf(page)
  await expect(editor.locator("#toothGrid > *")).not.toHaveCount(0)
  await editor.getByRole("option", { name: "16", exact: true }).click()
  const [mobilityValue] = await editor.locator("#mobilitySelect").selectOption({ index: 1 })
  await editor.locator("#calculusRow label").click()
  await expect(editor.locator("#calculusToggle")).toBeChecked()
  await page.screenshot({ path: "test-results/dental-light.png", fullPage: true })
  await page.getByRole("button", { name: "Cambiar tema" }).click()
  await expect(page.locator("html")).toHaveClass(/dark/)
  await expect(editor.locator("html")).toHaveClass(/dark/)
  const outerColor = await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue("--background").trim())
  await expect.poll(async () => editor.locator("html").evaluate((node) => getComputedStyle(node).getPropertyValue("--clinic-background").trim())).toBe(outerColor)
  await expect(page.getByRole("button", { name: "Guardar visita", exact: true })).toBeEnabled()
  await editor.locator("body").evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: "test-results/dental-dark.png", fullPage: true })

  await editor.locator("#appViewDentalChart").click()
  await expect(editor.locator("#perioInlinePanel")).toBeVisible()
  await page.screenshot({ path: "test-results/periodontogram.png", fullPage: true })
  // Inspect the actual measurement inputs, not a simulated replacement chart.
  const measurement = editor.locator('input[data-perio$=":pd"]').first()
  await expect(measurement).toBeVisible()
  const measurementKey = (await measurement.getAttribute("data-perio"))!
  await measurement.fill("5")
  await measurement.press("Tab")
  await editor.locator(`input[data-perio="${measurementKey.replace(":pd", ":gm")}"]`).fill("2")
  await editor.locator(`input[data-perio="${measurementKey.replace(":pd", ":gm")}"]`).press("Tab")
  await editor.locator(`input[data-perio="${measurementKey.replace(":pd", ":bop")}"]`).check()
  await editor.locator("button[data-furc-entrance]").first().click()
  await editor.locator("button[data-plaque-surface]").first().click()
  await expect(page.getByRole("button", { name: "Guardar visita", exact: true })).toBeEnabled()
  await editor.locator("#appViewOdontogram").click()

  await page.getByRole("tab", { name: "Evolución y diagnóstico", exact: true }).click()
  await page.getByLabel("Motivo de consulta", { exact: true }).fill("Control odontológico de prueba")
  await page.getByLabel("Diagnóstico", { exact: true }).fill("Registro de hallazgos de prueba")
  await page.getByLabel("Evolución por visita", { exact: true }).fill("Evolución documentada en la visita inicial")
  await page.getByLabel("Procedimientos realizados", { exact: true }).fill("Evaluación y registro")
  await page.getByLabel("Notas profesionales", { exact: true }).fill("Nota de prueba <script>window.injected=true</script>")
  await page.getByRole("tab", { name: "Plan de tratamiento", exact: true }).click()
  await page.getByLabel("Pieza / zona", { exact: true }).fill("16")
  await page.getByLabel("Procedimiento previsto", { exact: true }).fill("Procedimiento de prueba")
  await page.getByRole("button", { name: "Añadir al plan" }).click()
  await page.getByLabel("Estado de Procedimiento de prueba").selectOption("en-curso")

  await page.getByRole("tab", { name: "Consentimientos", exact: true }).click()
  await page.getByRole("button", { name: "Añadir consentimiento" }).click()
  await page.getByLabel("Procedimiento autorizado").fill("Evaluación de prueba")
  await page.getByLabel("Información, riesgos y alternativas explicados").fill("Información de ejemplo proporcionada al paciente")
  await page.getByLabel("Estado del consentimiento").selectOption("firmado")
  await page.getByLabel("Nombre del firmante").fill("Paciente de prueba")
  await page.getByLabel("Fecha de firma / decisión").fill("2026-09-20")

  await page.getByRole("tab", { name: "Fotos y documentos", exact: true }).click()
  const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jf1sAAAAASUVORK5CYII=", "base64")
  await page.getByLabel("Seleccionar archivos clínicos").setInputFiles({ name: "radiografia-prueba.png", mimeType: "image/png", buffer: png })
  await expect(page.getByText("radiografia-prueba.png", { exact: true })).toBeVisible()
  await expect(page.getByText("Guardando borrador…")).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole("button", { name: "Guardar visita", exact: true })).toBeEnabled()
  await page.getByRole("tab", { name: "Evolución y diagnóstico", exact: true }).click()
  await expect(page.getByLabel("Diagnóstico", { exact: true })).toHaveValue("Registro de hallazgos de prueba")
  await page.getByRole("button", { name: "Guardar visita", exact: true }).click()
  await expect(page.getByText("Visita guardada · solo lectura")).toBeVisible()
  await expect(page.getByRole("button", { name: "Historia completa JSON" })).toBeEnabled()
  const downloadPromise = page.waitForEvent("download")
  await page.getByRole("button", { name: "Historia completa JSON" }).click()
  const download = await downloadPromise
  const stream = await download.createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  const record = JSON.parse(Buffer.concat(chunks).toString())
  expect(record.visits).toHaveLength(1)
  expect(record.visits[0].attachments).toHaveLength(1)
  expect(record.visits[0].plan[0].status).toBe("en-curso")
  expect(record.visits[0].consents[0].status).toBe("firmado")
  const teeth = record.visits[0].chart.payload.teeth
  expect(teeth["16"].calculus).toBe(true)
  expect(teeth["16"].mobility).toBe(mobilityValue)
  expect(Object.values(teeth).some((tooth: any) => Object.values(tooth.perio?.pd ?? {}).includes(5))).toBe(true)
  const [measuredTooth, measuredSite] = measurementKey.split(":")
  expect(teeth[measuredTooth].perio.gm[measuredSite]).toBe(2)
  expect(teeth[measuredTooth].perio.bop).toContain(measuredSite)
  expect(Object.values(teeth).some((tooth: any) => Object.values(tooth.furcation ?? {}).some((grade) => Number(grade) > 0))).toBe(true)
  expect(Object.values(teeth).some((tooth: any) => tooth.plaque?.length > 0)).toBe(true)

  const documentPromise = page.waitForEvent("download")
  await page.getByRole("button", { name: "Documento de la visita", exact: true }).click()
  const document = await documentPromise
  const documentStream = await document.createReadStream()
  const documentChunks: Buffer[] = []
  for await (const chunk of documentStream!) documentChunks.push(Buffer.from(chunk))
  const html = Buffer.concat(documentChunks).toString()
  expect(html).toContain("&lt;script&gt;window.injected=true&lt;/script&gt;")
  expect(html).not.toContain("<script>")
  await page.getByRole("tab", { name: "Fotos y documentos", exact: true }).click()
  const attachmentPromise = page.waitForEvent("download")
  await page.getByRole("button", { name: "Descargar", exact: true }).click()
  const attachment = await attachmentPromise
  const fileStream = await attachment.createReadStream()
  const fileChunks: Buffer[] = []
  for await (const chunk of fileStream!) fileChunks.push(Buffer.from(chunk))
  expect(Buffer.concat(fileChunks)).toEqual(png)

  await page.getByRole("button", { name: "Nueva visita", exact: true }).click()
  await expect(page.getByLabel("Diagnóstico", { exact: true })).toHaveValue("")
  await page.getByLabel("Motivo de consulta", { exact: true }).fill("Segunda visita")
  await page.getByLabel("Diagnóstico", { exact: true }).fill("Segundo registro")
  await expect(page.getByRole("button", { name: "Guardar visita", exact: true })).toBeEnabled()
  await page.getByRole("button", { name: "Guardar visita", exact: true }).click()
  await page.getByRole("tab", { name: "Seguimiento por visita", exact: true }).click()
  await expect(page.getByRole("button", { name: "Consultar visita", exact: true })).toHaveCount(2)
  await page.getByRole("button", { name: "Consultar visita", exact: true }).last().click()
  await page.getByRole("tab", { name: "Evolución y diagnóstico", exact: true }).click()
  await expect(page.getByLabel("Diagnóstico", { exact: true })).toHaveValue("Registro de hallazgos de prueba")
  await expect(page.getByLabel("Diagnóstico", { exact: true })).toHaveAttribute("readonly", "")

  await openDental(page, "pat_2")
  await page.getByRole("tab", { name: "Evolución y diagnóstico", exact: true }).click()
  await expect(page.getByLabel("Diagnóstico", { exact: true })).toHaveValue("")
  await page.getByRole("tab", { name: "Fotos y documentos", exact: true }).click()
  await expect(page.getByText("radiografia-prueba.png", { exact: true })).toHaveCount(0)
  expect(errors).toEqual([])
})

test("recepción no puede acceder al módulo clínico", async ({ page }) => {
  await login(page, "recepcion")
  await page.goto("/historial-clinico/paciente/pat_1/odontologia")
  await expect(page).toHaveURL(/\/403$/)
  await expect(page.locator("iframe")).toHaveCount(0)
})
